# Generated by Django 3.2.5 on 2021-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoitems', '0003_auto_20210715_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='nanoitems.Tag'),
        ),
    ]
