# Generated by Django 3.2.5 on 2021-07-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoitems', '0004_auto_20210715_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
